### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456"
}

### signin user (valid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}


### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456",
    "workspace":"acme"
}

### signin user (valid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}

### signin user (invalid)

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}


### get chat list


GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}


### get user list
GET  http://localhost:6688/api/users
Authorization: Bearer {{token}}

### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="BB1pZoqX.png"
Content-Type: application/octet-stream

< /download/BB1pZoqX.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files

GET http://localhost:6688/api/files/1/2c2/509/2c2509ed023a13ce03e8dd25b9db54551ab12b4f.png
Authorization: Bearer {{token}}
